### PR TITLE
update basic to latest ci-plugin

### PR DESCRIPTION
**Pull request by lloydbenson**

### CODE REVIEW

**Review by geek — APPROVED** [review]

**Review by Nargonath — APPROVED** [review]

**Comment by Nargonath** [comment]
I believe we added recently `node@17` to `hapi` CI configuration. I wonder if we should do the same for the rest of the org. I hope GitHub will add a template feature as GitLab because it's quite painful to maintain otherwise. 😅

**Comment by kanongil** [comment]
I don't think '*' actually uses v17. As far as I can tell it uses the latest from this page: https://github.com/actions/node-versions/releases.

**Comment by Nargonath** [comment]
Hum that'd be a pity if it does use the latest available mention be it LTS or not. Perhaps at some point v17 will be part of this before v18 comes out. 🤔

**Comment by devinivy** [comment]
Can confirm that in my experience `*` takes the latest LTS version available 👍 So it will always be an even version.

**Comment by Nargonath** [comment]
I have nothing against having `hapi` tested against `node@17`.

**Comment by kanongil** [comment]
One option to make it work better for hapi, and possibly centralize some config, would be to fork https://github.com/actions/setup-node and make a hapi node runner.

**Comment by Nargonath** [comment]
There is already an issue (https://github.com/actions/setup-node/issues/257) on `setup-node` regarding adding `current | latest` keyword to use the latest `node` version and not only the `lts` versions. I'd prefer using this new feature than for us to maintain another fork.

**Comment by kanongil** [comment]
Makes sense. Btw, it seems that github now has better template support, called reusable workflows: https://dev.to/github/github-actions-you-can-build-reusable-workflows-4gc7

**Comment by Nargonath** [comment]
That's so cool! I've waiting for this for a long time. Thanks for sharing @kanongil. I guess we can put this MR on hold until we figure out how to use it. I'll try to spin up a PR for it if I have the time this weekend.

**Comment by lloydbenson** [comment]
Closing in favor of #89.

**Pull request closed without merging**
